language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda
  - conda activate test-environment
  - conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
  - conda install -c conda-forge opencv
  - conda install ignite -c pytorch
  - conda install -c conda-forge h5py
  - conda install scikit-learn
  - conda install -c anaconda pillow
  - conda install -c anaconda numpy
  - conda install -c anaconda matplotlib
  - pip install comet_ml
# command to run tests
script:
  - pytest data_util